# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgs < Formula
  desc "Thought-Guided Software development workflow CLI"
  homepage "https://github.com/akelv/tgsflow"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akelv/tgsflow/releases/download/v0.0.3/tgs_0.0.3_darwin_amd64.tar.gz"
      sha256 "c11d79e3ff17e0dc857c84d4c8d0c2f105d8b26f268e70f7ca479504b3fab913"

      def install
        bin.install "tgs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akelv/tgsflow/releases/download/v0.0.3/tgs_0.0.3_darwin_arm64.tar.gz"
      sha256 "a1a9121f397bf123e56a6803808c01f01d1a9bf5003d42fefb699dda0ff2d7fd"

      def install
        bin.install "tgs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akelv/tgsflow/releases/download/v0.0.3/tgs_0.0.3_linux_amd64.tar.gz"
      sha256 "ecedd7b0a0a03ccc4bada302833e58af306f55f8a5d8cd27dff199d62c9c315e"
      def install
        bin.install "tgs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akelv/tgsflow/releases/download/v0.0.3/tgs_0.0.3_linux_arm64.tar.gz"
      sha256 "1727746f0bcd37a8cd05ea14c1523791930a76f6568924c2cdc0332e6a8ec7b9"
      def install
        bin.install "tgs"
      end
    end
  end

  test do
    system "#{bin}/tgs", "--version"
  end
end
