# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgs < Formula
  desc "Thought-Guided Software development workflow CLI"
  homepage "https://github.com/akelv/tgsflow"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akelv/tgsflow/releases/download/v0.0.2/tgs_0.0.2_darwin_amd64.tar.gz"
      sha256 "42137f4696cd7c893f5369af21b6afdeaecf39f97d04217496d6811d72f33d9c"

      def install
        bin.install "tgs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akelv/tgsflow/releases/download/v0.0.2/tgs_0.0.2_darwin_arm64.tar.gz"
      sha256 "d838ed8777d85c3b508ab59e08e6310bc752ed1efd7b1f6eaa9ce9dc91209915"

      def install
        bin.install "tgs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akelv/tgsflow/releases/download/v0.0.2/tgs_0.0.2_linux_amd64.tar.gz"
      sha256 "06b3026f91529352b38d8718525246a6861bb3ef92ea700e8297ef4f3859c393"
      def install
        bin.install "tgs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akelv/tgsflow/releases/download/v0.0.2/tgs_0.0.2_linux_arm64.tar.gz"
      sha256 "f7586cb91af96893d8a2be249a0cf40a019d731d841b511388f6260ee8d79fc1"
      def install
        bin.install "tgs"
      end
    end
  end

  test do
    system "#{bin}/tgs", "--version"
  end
end
